[Config]
MinimumVersion=25

[Include]
Include=mkosi-initrd

[Distribution]
Distribution=fedora
Release=41
Architecture=arm64

[Output]
ImageId=rescueshell
Output=
Format=directory
ManifestFormat=json
#SplitArtifacts=yes
SectorSize=512

[Build]
Incremental=yes
CacheDirectory=%D/mkosi.cache
ToolsTreePackages=dnf-plugins-core

[Content]
MakeInitrd=no
# Configure locale explicitly so that all other locale data is stripped on distros whose package manager supports it.
Locale=C.UTF-8
LocaleMessages=C.UTF-8
Keymap=us
Timezone=UTC

# Keep shadow-utils for rescue root (removed by the default mkosi-initrd config)
RemovePackages=
RemovePackages=dracut*
# For some reason a .viminfo file sometimes appear in the root of the
# destination image, probably my own fault but let's delete it if it happens.
RemoveFiles=.viminfo

# This does not seem to have any effect when not building an initrd file
#FirmwareExclude=.*
#FirmwareInclude=
#FirmwareInclude=tegra
#FirmwareInclude=nvidia

# Remove some big firmware blobs which are useless on our rescue image
RemoveFiles=
  /usr/lib/firmware/amd*
  /usr/lib/firmware/intel
  /usr/lib/firmware/xe
  /usr/lib/firmware/mediatek
  /usr/lib/firmware/amlogic
  /usr/lib/firmware/*wifi*
  /usr/lib/firmware/cxgb*
  /usr/lib/firmware/dpaa*
  /usr/lib/firmware/qat*
  /usr/lib/firmware/s5p*

# To save some 50 MiB, although usbutils, wget and zchunk will be uninstalled
#RemovePackages=
#  python3
#  python3-libs


# Skip weak dependencies
WithRecommends=no
WithDocs=no
CleanPackageMetadata=yes
#Bootable=yes
#Bootloader=systemd-boot

# Rescue tools and hardware debug
Packages=
  dtc
  coreutils
  util-linux
  efibootmgr
  xfsprogs
  dosfstools
  e2fsprogs
  erofs-utils
  btrfs-progs
  squashfs-tools
  composefs
  iproute
  ethtool
  dhcp-client
  # systemd-networkd has fewer dependencies than NetworkManager and is smaller on the image size
  #NetworkManager
  systemd-networkd
  systemd-resolved
  usbutils
  pciutils
  openssl
  iputils
  curl
  ca-certificates
  wget
  wireguard-tools
  net-tools
  linux-firmware
  zstd
  xz
  zip
  gzip
  bzip2
  tar
  cpio
  lz4
  sed
  gawk
  patch
  vim-minimal
  nano
  less
  ncurses
  bash
  bash-color-prompt
  nvme-cli
  smartmontools
  dmidecode
  shadow-utils
  passwd
  device-mapper
  cryptsetup
  acl
  attr
  grep
  diffutils
  findutils
  procps-ng
  systemd-boot
  bash-completion
  gdisk
  openssh-clients
  mtd-utils
  keyutils
  parted
  sbsigntools
  veritysetup
  integritysetup
  jq
  sudo
  tzdata
  lvm2
  udev
  zchunk
  audit-libs
  cracklib-dicts
  distribution-gpg-keys
  glibc-minimal-langpack
  git-core
  kbd
  watchdog
  mokutil
  socat
  nmap-ncat

#Packages=
#  nmap
#  bind-utils
#  iptables-nft
#  iproute-tc
#  unbound-libs
#  chrony
#  nss
#  nss-tools
#  gnupg2
#  libkcapi-hasher
#  libkcapi-hmaccalc
#  ima-evm-utils
#  p11-kit
#  p11-kit-trust
#  qrencode
#  moreutils
#  zsh
#
