[Config]
MinimumVersion=25

[Include]
Include=mkosi-initrd

[Distribution]
Distribution=fedora
Release=41
Architecture=arm64

[Output]
ImageId=rescueshell
Output=
Format=directory
ManifestFormat=json
#SplitArtifacts=yes
SectorSize=512

[Build]
Incremental=yes
CacheDirectory=%D/mkosi.cache
ToolsTreePackages=dnf-plugins-core

[Content]
MakeInitrd=no
# Configure locale explicitly so that all other locale data is stripped on distros whose package manager supports it.
Locale=C.UTF-8
LocaleMessages=C.UTF-8
Keymap=us
Timezone=UTC

RemovePackages=
RemovePackages=dracut*
RemoveFiles=.viminfo

# Rescue tools and hardware debug
Packages=
  dtc
  coreutils
  util-linux
  efibootmgr
  xfsprogs
  dosfstools
  e2fsprogs
  erofs-utils
  btrfs-progs
  squashfs-tools
  composefs
  iproute
  ethtool
  dhcp-client
  NetworkManager
  usbutils
  pciutils
  openssl
  iputils
  curl
  ca-certificates
  wget
  wireguard-tools
  net-tools
  linux-firmware
  zstd
  xz
  zip
  gzip
  bzip2
  tar
  cpio
  lz4
  sed
  gawk
  patch
  vim
  nano
  vim-default-editor
  less
  ncurses
  bash
  bash-color-prompt
  nvme-cli
  smartmontools
  dmidecode
  shadow-utils
  passwd
  device-mapper
  cryptsetup
  acl
  attr
  grep
  diffutils
  findutils
  procps-ng
  systemd-boot
  bash-completion
  gdisk
  openssh-clients
  mtd-utils
  keyutils
  parted
  sbsigntools
  veritysetup
  integritysetup
  jq
  sudo
  tzdata
  lvm2
  udev
  zchunk
  audit-libs
  cracklib-dicts
  distribution-gpg-keys
  glibc-minimal-langpack
  git-core
  kbd
  watchdog
  mokutil
  socat
  nmap-ncat

#Packages=
#  nmap
#  bind-utils
#  iptables-nft
#  iproute-tc
#  unbound-libs
#  chrony
#  nss
#  nss-tools
#  gnupg2
#  libkcapi-hasher
#  libkcapi-hmaccalc
#  ima-evm-utils
#  p11-kit
#  p11-kit-trust
#  qrencode
#  moreutils
#  zsh
#
